import numpy as np
import torch
from sklearn.model_selection import train_test_split


def load_and_prepare_data(PATH_DATA, cfg):
    """
    This function reads the dataset and prepares the relevant physical fields and parameters.
    Sparse measurement data (later input-only training data) is generated by sampling the surface elevation at
    predefined buoy locations within the interior of the spatial domain.
    :param PATH_DATA: path to the dataset file
    :param cfg: configuration object (defined in config.py) containing parameters such as number of buoys and boundary exclusion fraction.
    :return eta_true: true surface elevation field of shape (n_samples, nx, nt), used for synthetic measurement data generation and post-training comparison only
    :return eta_meas: sparse elevation measurements at buoy locations, shape (n_samples, num_buoys, nt), used as PINO-input
    :return phi_true: true surface potential field of shape (n_samples, nx, nt), used for post-training comparison only
    :return info_Ls_eps: array of shape (n_samples, 2) containing peak wavelength (Lp) and steepness (eps) for each sample
    :return x: spatial grid coordinates
    :return t: temporal grid coordinates
    :return buoy_ind : list of indices of spatial grid points where buoys are placed.
    """

    # --- load data ---
    data = np.load(PATH_DATA, mmap_mode='r')
    x = data['X'][:, 0]
    t = data['T'][0, :]
    eta_true = data['eta_true'].astype(np.float32).squeeze(-1)      # true elevation
    phi_true = data['phi_true'].astype(np.float32).squeeze(-1)      # true surface potential
    info_Ls_eps = np.hstack((data['info_Ls'][:, None], data['info_eps'][:, None])).astype(np.float32)  # peak wavelength (Lp) and steepness (eps) corresponding to each sample

    # --- place buoys uniformly within the interior area ---
    nx = len(x)
    margin = int(cfg.space_boundary_exclusion * nx)
    buoy_ind = np.linspace(margin, nx - margin - 1, cfg.num_buoys).astype(int).tolist()

    # --- extract sparse measurements as input-only training data ---
    eta_meas = eta_true[:, buoy_ind, :]         # eta_meas serves as sparse input to the PINO model, mimicking real buoy observations

    return eta_true, eta_meas, phi_true, info_Ls_eps, x, t, buoy_ind


def split_data_and_create_dataloaders(eta_true, phi_true, eta_meas, info_Ls_eps, cfg):
    """
    Split dataset into training, validation, and test sets and create PyTorch DataLoaders:
    The data are split in two stages using stratified splits based on the physical parameters (Lp and eps).
    The resulting subsets are rapped into PyTorch DataLoaders for efficient batching during training and evaluation.
    :param eta_true: true surface elevation field of shape (n_samples, nx, nt), used for synthetic measurement data generation and post-training comparison only
    :param phi_true: true surface potential field of shape (n_samples, nx, nt), used for post-training comparison only
    :param eta_meas: sparse elevation measurements at buoy locations, shape (n_samples, num_buoys, nt), used as PINO-input
    :param info_Ls_eps: array of shape (n_samples, 2) containing peak wavelength (Lp) and steepness (eps) used for stratified data splitting
    :param cfg: configuration object (defined in config.py) containing parameters such as batch size, test/validation split ratio, and data loader settings.
    :return train_loader: DataLoader for the training set, provides (eta_meas, eta_true, info) while only eta_meas serves as input (eta_true just to calculate the metrics during training)
    :return val_loader: DataLoader for the validation set, provides (eta_meas, eta_true, info) while only eta_meas serves as input (eta_true just to calculate the metrics during training)
    :return test_loader: DataLoader for the test set, provides (eta_meas, eta_true, phi_true, info) while only eta_meas serves as input (eta_true, phi_true just to calculate the metrics during training)
    """

    # --- first stratified data split (train vs val+test) ---
    eta_true_train, eta_true_val, phi_true_train, phi_true_val, eta_meas_train, eta_meas_val, info_train, info_val = train_test_split(
        eta_true, phi_true, eta_meas, info_Ls_eps, test_size=cfg.test_val_size, random_state=10, stratify=np.sum(info_Ls_eps, dtype=np.float64, axis=1))

    # --- second stratified data split (val vs. test) ---
    eta_true_test, eta_true_val, phi_true_test, phi_true_val, eta_meas_test, eta_meas_val, info_test, info_val = train_test_split(
        eta_true_val, phi_true_val, eta_meas_val, info_val, test_size=0.5, random_state=10, stratify=np.sum(info_val, dtype=np.float64, axis=1))

    # --- data loader settings ---
    persistent_workers = cfg.num_workers > 0
    prefetch_factor = cfg.prefetch_factor if cfg.num_workers > 0 else None

    # --- data loaders ---
    train_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(torch.from_numpy(eta_meas_train),
                                       torch.from_numpy(eta_true_train),
                                       torch.from_numpy(info_train)),
        batch_size=cfg.batch_size, shuffle=True, pin_memory=True, num_workers=cfg.num_workers,
        persistent_workers=persistent_workers, prefetch_factor=prefetch_factor)

    val_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(torch.from_numpy(eta_meas_val),
                                       torch.from_numpy(eta_true_val),
                                       torch.from_numpy(info_val)),
        batch_size=cfg.batch_size, shuffle=False, pin_memory=True, num_workers=cfg.num_workers,
        persistent_workers=True, prefetch_factor=prefetch_factor)

    test_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(torch.from_numpy(eta_meas_test),
                                       torch.from_numpy(eta_true_test),
                                       torch.from_numpy(info_test),
                                       torch.from_numpy(phi_true_test)),  # test loader with additional phi_true for post-training comparison
        batch_size=cfg.batch_size, shuffle=False, pin_memory=True, num_workers=cfg.num_workers,
        persistent_workers=True, prefetch_factor=prefetch_factor)

    print(f"training samples: {len(train_loader.dataset)}")
    print(f"validation samples: {len(val_loader.dataset)}")
    print(f"test samples: {len(test_loader.dataset)}")

    return train_loader, val_loader, test_loader
